---
title: "Calculating the Average Age of NBA Teams"
author: "kyle wurtz"
date: "September 16, 2016"
output:
  html_document:
    toc: true
    theme: yeti
    code_folding: hide
---

## Overview

Tweets that prompted this investigation:

- https://twitter.com/denbutsu/status/776051018157076480
- https://twitter.com/denbutsu/status/776050618175586304

## Setup

### Load Packages
```{r load packages, warning = FALSE, message = FALSE}
require(tidyverse)
require(magrittr)
require(rvest)
require(ggthemes)
require(pander)
```

## Work

### Scraping the Data


```{r scrape totals}
player_totals = read_html("http://www.basketball-reference.com/leagues/NBA_2016_totals.html")

player_totals %<>% 
  html_node("#totals_stats") %>% 
  html_table()
```

```{r clean up table}
# glimpse(player_totals)

# convert to tibble
player_totals %<>% as_tibble()

# remove row breaks
player_totals %<>% filter(Rk != "Rk")

# remove "TOT" values for players who spent time on multiple teams
player_totals %<>% filter(Tm != "TOT")
```

### Plotting Average Ages

```{r get average age of every team weighted by minutes played, fig.width = 12, fig.height = 7}
player_totals %>% 
  group_by(Tm) %>% 
  mutate(
    Age = as.numeric(Age),
    MP = as.numeric(MP)
  ) %>% 
  summarize(
    wtd_mean_age = weighted.mean(Age, MP),
    mean_age = mean(Age)
  ) %>% 
  arrange(wtd_mean_age) %>% 
  mutate(Tm = factor(Tm, levels = .[[1]])) %>% 
  ggplot(., aes(x = Tm, y = wtd_mean_age, fill = mean_age)) +
    geom_bar(stat = "identity") +
    coord_cartesian(ylim = c(20, 32)) +
    theme_fivethirtyeight() +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5)) +
    ggtitle("Average Age of NBA Teams") +
    theme(axis.title = element_text(), 
          axis.title.x = element_blank(), 
          axis.title.y = element_text(margin = margin(0, 15, 0, 0))) + 
    ylab('Avg. Age (Wtd. by MP)') +
    scale_fill_continuous("Avg. Age (Not Weighted)", low = "#56B1F7", high = "#132B43")
```

### Listing Average Ages and Youngest Ranks

```{r also show the data in tabular form}
player_totals %>% 
  group_by(Tm) %>% 
  mutate(
    Age = as.numeric(Age),
    MP = as.numeric(MP)
  ) %>% 
  summarize(
    wtd_mean_age = weighted.mean(Age, MP),
    mean_age = mean(Age)
  ) %>% 
  mutate(
    rnk_wtd = min_rank(wtd_mean_age),
    rnk_not_wtd = min_rank(mean_age),
    wtd_mean_age = round(wtd_mean_age, 1),
    mean_age = round(mean_age, 1)
  ) %>% 
  arrange(wtd_mean_age) %>% 
  pander()
```


## Conclusion